import Header from '../components/Header';
import Interactive,{Work,Offer,FAQ} from '../components/Interactive';
import Contact from '../components/Contact';
import ActionButton from '../components/ActionButton';
const wa='https://wa.me/2347017285626';
const Btn=({children,lime=false,modal='Get Started'})=><ActionButton lime={lime} modal={modal}>{children}</ActionButton>;
const WA=({children='WhatsApp Us'})=><a className="cta wa-cta" href={wa} target="_blank" rel="noopener noreferrer">{children}</a>;
const Actions=({children})=><div className="actions">{children}</div>;
const journey=[['Discovery','They hear about your business.'],['Research','They look you up online.'],['Experience','They visit your website.'],['Decision','They take action or leave.']];
const principles=[['Business first','We start with what you are trying to achieve, not a template.'],['Clear by design','We make it easy for people to understand what you offer and what to do next.'],['Built to grow','Start with what you need now. Add what makes sense as your business grows.']];
const steps=[['Tell us what you need','Give us the basics about your business, your customers and what you want your website to achieve.'],['We build','We turn your information into a clear, professional website built around your business.'],['You review','See the finished site, tell us what needs changing and approve it when you are happy.'],['Go live','We connect your domain, complete the final checks and put your website to work.']];
export default function Home(){return <><Header/><main>
<section className="hero section" id="home"><div className="hero-grid"><div><div className="eyebrow">GoReallyBig</div><h1>Your Business Is Ready To Go Really <span>Big.</span></h1><p className="lead">Start with a professional website that makes your business look credible, gets you found online, and turns your visitors into customers. At <strong>GoReallyBig</strong>, our job is to make your website <strong className="navy">make money for you.</strong></p><Actions><Btn>Get Started</Btn><WA/></Actions></div><figure className="hero-visual"><img src="/assets/c04-hero.png" alt="Evergreen Private School website design mockup"/></figure></div></section>
<section className="problem section" id="problem"><div className="wrap"><div className="eyebrow">Your online presence</div><h2>First Impressions Happen Before the First Conversation</h2><p className="problem-copy">When potential clients research your business online, what they discover determines whether they reach out, or walk away.</p><p className="problem-copy">Take a close look at your digital footprint:</p><div className="problem-subsection"><div><div className="questions"><div className="q"><strong>Clarity</strong><span>Can visitors tell what you do in under 3 seconds?</span></div><div className="q"><strong>Credibility</strong><span>Is there enough proof to earn immediate trust?</span></div><div className="q"><strong>Action</strong><span>Is taking the next step completely friction-free?</span></div></div><p className="problem-copy"><strong>If your current online presence leaves any of these questions unanswered, you are leaving revenue on the table.</strong></p><p className="problem-final"><strong>Does your website convert, or just exist?</strong></p><Btn lime modal="Get Your Free Website Audit">Get Your Free Website Audit</Btn></div><img className="problem-visual" src="/assets/c06-problem.png" alt="Website problem visual"/></div></div></section>
<section className="promise section"><div className="wrap"><div className="promise-head"><div className="eyebrow">The promise</div><h2>Your website should have one primary job.</h2><p className="lead"><strong>Capture interest. And turn it into business.</strong></p><p className="lead">That is what we build. Websites that make your business easy to find, easy to trust and easy to choose.</p><p className="lead"><strong>Need a fresh new website?</strong> We will build it right.<br/><strong>Already have one that is not performing?</strong> We will bring it back to life.</p></div><div className="promise-layout"><div className="promise-flow">{[['⌕','GET FOUND','Make it easier for the right people to discover your business and understand what you offer.'],['✓','BUILD TRUST','Give them a professional first impression that matches the quality of your business.'],['↗','WIN THE BUSINESS','Turn interest into calls, messages, enquiries and customers.']].map(([i,t,d],n)=><article className="promise-card" key={t}><div className="promise-icon">{i}</div><div className="num">0{n+1}</div><h3>{t}</h3><p>{d}</p></article>)}</div><figure className="promise-visual"><img src="/assets/c07-promise.png" alt="GoReallyBig website visual showing get found, build trust and win the business"/><figcaption>One website. Three jobs: get found, build trust, win the business.</figcaption></figure></div><Actions><Btn>Get Started</Btn><WA>Message Us</WA></Actions></div></section>
<Interactive/>
<section className="opportunity section"><div className="wrap"><div className="eyebrow">The commercial moment</div><h2>The Moment That Matters</h2><p className="lead">Before a client ever reaches out, they first look you up online.<br/>In just a few seconds on your website, they decide whether to trust you, or walk away.</p><h3 className="subhead">How Visitors Become Clients</h3><div className="journey">{journey.map(([t,d],i)=><div className="journey-step" key={t}><div className="node">0{i+1}</div><div><b>{t}</b><p>{d}</p></div></div>)}</div><div className="opportunity-close"><strong>Be ready when they arrive.</strong><Actions><Btn>Get Started</Btn><WA>Talk To Us</WA></Actions></div></div></section>
<section className="about section" id="about"><div className="wrap"><div className="eyebrow">Our approach</div><div className="about-head"><h2>Why GoReallyBig</h2><div><p className="lead"><strong>We do not just make websites. We make them work.</strong></p><p className="lead">We think about your business first, your customers second and the technology third. Every page, message and action has a reason to be there.</p></div></div><div className="about-subsection"><div className="principles">{principles.map(([t,d],i)=><article className="principle" key={t}><div className="n">0{i+1}</div><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><figure className="about-visual"><img src="/assets/auto-drive-motors.png" alt="AutoDrive Motors professional business website mockup"/><figcaption>Business first. Customers next. Technology where it matters to the business growth.</figcaption></figure></div><Actions><Btn>Get Started</Btn></Actions></div></section>
<section className="process section"><div className="wrap"><div className="eyebrow">How we work</div><h2>From idea to online. Without the headache.</h2><p className="lead process-intro">Tell us about your business. We handle the website. You review it. Then we get you live.</p><div className="process-map">{steps.map(([t,d],i)=><article className="process-card" key={t}><div className="process-node">0{i+1}</div><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><div className="process-close">You do not need to know anything about websites. That is our job.</div><Actions><Btn>Get Started</Btn><WA>Chat With Us</WA></Actions></div></section>
<section className="work section" id="work"><div className="wrap"><div className="work-top"><div><div className="eyebrow">Our work</div><h2>See what your business could look like.</h2></div><p className="lead">Clean design. Clear messaging. Websites built around what your customers need to see, know and do.</p></div><Work/><div className="makeover"><div><h3>Already have a website?</h3><p>We can refresh, restructure or rebuild it to make it work harder for your business.</p></div><Actions><Btn modal="Get Your Website">Get Your Website</Btn><WA>Message Us</WA></Actions></div><p className="work-close">Your business does not need to look like everyone else. It needs to look like a business worth choosing.</p></div></section>
<section className="offer section" id="offer"><div className="wrap"><div className="offer-head"><div className="eyebrow lime-text">The offer</div><h2>Built around your business. Priced for what you need.</h2><p>Every GoReallyBig website starts with the essentials. We then tailor the scope to your business and give you a clear price before we start.</p></div><Offer/></div></section>
<section className="faq section" id="faq"><div className="wrap faq-grid"><div><div className="eyebrow">Questions</div><h2>Questions? We have answers.</h2><p className="lead">Everything you need to know about how GoReallyBig works.</p><Actions><Btn>Get Started</Btn><WA>Talk To Us</WA></Actions></div><FAQ/></div></section>
<Contact/></main><footer className="footer"><div className="footer-inner"><div className="footer-brand"><a href="#home"><img className="footer-logo" src="/assets/footer-logo-transparent.png" alt="GoReallyBig"/></a><p>Professional websites built to make businesses easier to find, easier to trust and easier to choose.</p><span className="footer-tagline">go. really. big.</span></div><nav className="footer-nav"><h3>Explore</h3>{[['Home','home'],['Services','services'],['About','about'],['Our Work','work'],['The Offer','offer'],['FAQ','faq'],['Contact','contact']].map(([x,id])=><a href={'#'+id} key={id}>{x}</a>)}</nav><div className="footer-contact"><h3>Get in touch</h3><a className="footer-contact-link" href="mailto:info@goreallybig.com"><span>Email</span><strong>info@goreallybig.com</strong></a><a className="footer-contact-link" href={wa} target="_blank" rel="noopener noreferrer"><span>WhatsApp</span><strong>+234 701 728 5626</strong></a><span className="footer-social-label">Follow GoReallyBig</span><div className="socials footer-socials">{['Facebook','Instagram','TikTok','X'].map(x=><a href="#" aria-label={x} key={x}>{x[0]}</a>)}</div><span className="footer-tagline-mobile">go. really. big.</span></div></div><div className="footer-bottom"><span>© GoReallyBig</span><span>Professional web presence for ambitious businesses.</span></div></footer></>}
